version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/ticketdb"

  db:
    image: postgres:latest
    container_name: ticket-db
    ports:
      - "5434:5432"
    volumes:
      - ticket-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ticketdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  ticket-data:


