version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    platform: linux/arm64
    ports:
      - "3000:3000"
    networks:
      - buraknet
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: ticket-db
    ports:
      - "5434:5432"
    volumes:
      - ticket-data:/var/lib/postgresql/data
    networks:
      - buraknet
    environment:
      POSTGRES_DB: ticketdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  ticket-data:

networks:
  buraknet:
