version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/ticketdb"
      REDIS_URL: "redis://redis:6379"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    working_dir: /app
    command: ng serve --host 0.0.0.0 --port 4200 --poll=2000 --disable-host-check
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development


  db:
    image: postgres:latest
    container_name: ticket-db
    ports:
      - "5434:5432"
    volumes:
      - ticket-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ticketdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:latest
    container_name: ticket-redis
    ports:
      - "6379:6379"

volumes:
  ticket-data:
  frontend_node_modules:
  backend_node_modules: