services:
  - type: web
    name: backend
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:postgres@ticket-db:5432/ticketdb
      - key: REDIS_URL
        value: redis://ticket-redis:6379
    autoDeploy: true

  - type: web
    name: frontend
    env: docker
    plan: free
    dockerfilePath: frontend/Dockerfile
    buildCommand: npm install
    startCommand: ng serve --host 0.0.0.0 --port 4200 --poll=2000 --disable-host-check
    envVars:
      - key: NODE_ENV
        value: development
    autoDeploy: true

  - type: pserv
    name: ticket-db
    plan: free
    image: postgres:latest
    envVars:
      - key: POSTGRES_DB
        value: ticketdb
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        value: postgres

  - type: pserv
    name: ticket-redis
    plan: free
    image: redis:latest
